server:
  port: 8888
  
spring:  cloud:    config:
      server:
        git: 
          uri: https://github.com/franrbb/bootcamp-configServer
          default-label: main
          search-paths:
          - '*service'
        